# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e97724872434f33b706ddc6cdbbcf42e8e69c3c91ea23aa7cc58b51db57e3ed75ea3b56405d857338ff7c60c31dcda6ea1d9d18e92965571b700f7c12e87e17a

test:
  secret_key_base: 8adb4c74540fbe74bb087911bb9ea9a10b0840ef9a36efff0974b8623b4be6c694fbe69393c9cba45515cd1d0a9916d1da5cc6647c007e78b4d316bc330b671c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
